### ISSUE TITLE
Unable to close modal correctly

### ISSUE THREAD

**Issue by tkovacik** [rgabs/react-native-modal-overlay#7]
Just installed, after modal is being hidden, the background color came back

**Comment by rgabs** [comment]
You need to pass onClose prop. Change to visibility to false onClose and it
will work.

**Comment by tkovacik** [comment]
Working, thanx 👍

**Comment by carinlynchin** [comment]
curious about this code though... it is called when closeOnTouchOutside is true:

 ```
_hideModal = () => {
    const {animationOutType, animationDuration, onClose} = this.props;
    this.setState({animationType: animationOutType, overlayAnimationType: animationOutType});
    let timer = setTimeout(() => {
      onClose();
      clearTimeout(timer);
      this.setState({overlayAnimationType: 'fadeIn'});
    }, animationDuration - 100);
  }
```

why is it setting fadeIn after the timer is done? that is what caused the background to come back.

**Comment by http-victor** [comment]
Yes, I am facing the same issue. @tkovacik could you provide the code that made this work? I tried using closeOnTouchOutside and set the boolean to true, however, that didn't seem to work.

**Comment by rgabs** [comment]
@http-victor The onClose prop is required for the component to work. Please have a look [here](https://github.com/rgabs/react-native-modal-overlay#examples) for examples.

**Comment by rgabs** [comment]
@carinlynchin We are setting overlayAnimationType to fadeIn to reset the component to the original state.

**Comment by rgabs** [comment]
> curious about this code though... it is called when closeOnTouchOutside is true:
> 
> ```
> _hideModal = () => {
>    const {animationOutType, animationDuration, onClose} = this.props;
>    this.setState({animationType: animationOutType, overlayAnimationType: animationOutType});
>    let timer = setTimeout(() => {
>      onClose();
>      clearTimeout(timer);
>      this.setState({overlayAnimationType: 'fadeIn'});
>    }, animationDuration - 100);
>  }
> ```
> why is it setting fadeIn after the timer is done? that is what caused the background to come back.

@carinlynchin We are setting overlayAnimationType to fadeIn to reset the component to the original state.
