### ISSUE TITLE
ScrollView component not scrollable within the overlay?

### ISSUE THREAD

**Issue by slarsendisney** [rgabs/react-native-modal-overlay#9]

**Comment by niklassaers** [comment]
I'm struggling with the same issue - adding a ScrollView inside of the overlay, I cannot get it to scroll

**Comment by Thomasn57** [comment]
Hello, I'm facing the same issue, any update on that?

**Comment by ridwan85** [comment]
Try wrapping the scrollview inside a view and put the following 

`<View style={{ height: 300, width: "100%", alignItems: "center" }}>`
          `<ScrollView`
            `style={{ marginTop: 20, width: "100%", marginLeft: 0 }}`
         `>`
           ` ...`
         ` </ScrollView>`
       ` </View>`

**Comment by jeremybarbet** [comment]
I have been working on react-native-modalize that fixed this kind of scrollable behavior: https://github.com/jeremybarbet/react-native-modalize

**Comment by hazelf42** [comment]
Also having this issue FWIW, @ridwan85's solution didn't work for me
